---

- name: Preparing envoriment
  remote_user:  "{{ remote_user }}"
  become: yes
  hosts: all
  tasks:

    - name: Uninstall old versions
      apt:
        name:
          - docker 
          - docker-engine 
          - docker.io 
          - containerd 
          - runc
        state: absent
    
    - name: Set up the repository
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: latest
        update_cache: yes

    - name: Add Docker’s official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Set up the stable repository
      shell: echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      args:
        executable: /bin/bash
      
    - name: Install Docker Engine
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        update_cache: yes
    
    - name: Adding existing user "{{ docker_user }}" to group sudo
      user:
        name: "{{ docker_user }}"
        groups: docker
        append: yes
